version: "3.1"

services:

  atsea-db:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    image: atsea-db
    ports:
      - "1433:1433"
    networks:
      - app-net

  atsea-api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: atsea-api
    ports:
      - "8080:8080" 
    depends_on:
      - atsea-db
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat